VictoryRoad_1F_Text_NaomiIntro::
    .string "I wonder if you are good enough\n"
    .string "for me?$"

VictoryRoad_1F_Text_NaomiDefeat::
    .string "I lost out…$"

VictoryRoad_1F_Text_NaomiPostBattle::
    .string "I never wanted to lose to anybody,\n"
    .string "especially to a younger kid…$"

VictoryRoad_1F_Text_RolandoIntro::
    .string "I can see you're good.\n"
    .string "Let me see exactly how good!$"

VictoryRoad_1F_Text_RolandoDefeat::
    .string "I had a chance…$"

VictoryRoad_1F_Text_RolandoPostBattle::
    .string "Tch!\n"
    .string "I concede, you are better than I!$"


VictoryRoad_1F_Text_VictorIntro::
	.string "I started with BUG POKéMON.\n"
	.string "Look how far we've come!$"

VictoryRoad_1F_Text_VictorDefeat::
	.string "Squashed!$"

VictoryRoad_1F_Text_VictorPostBattle::
	.string "Never let anyone laugh at\n"
	.string "your first partner.$"

VictoryRoad_1F_Text_ViolaIntro::
	.string "Strength can be elegant, too.\n"
	.string "Allow me to demonstrate!$"

VictoryRoad_1F_Text_ViolaDefeat::
	.string "How inelegant of me!$"

VictoryRoad_1F_Text_ViolaPostBattle::
	.string "The LEAGUE is close. Fix your\n"
	.string "hair before the cameras!$"

VictoryRoad_1F_Text_SidIntro::
	.string "Heh… I'm here to steal\n"
	.string "the title of CHAMPION!$"

VictoryRoad_1F_Text_SidDefeat::
	.string "Caught red-handed!$"

VictoryRoad_1F_Text_SidPostBattle::
	.string "Some treasures can't be stolen.\n"
	.string "They must be earned…$"
