JohtoIsle_Chuck_Text_LeaderPreBattle::
	.string "I am CHUCK, master of this\n"
	.string "isle. Show me your resolve!$"

JohtoIsle_Chuck_Text_LeaderIntro::
	.string "Let's battle!$"

JohtoIsle_Chuck_Text_LeaderDefeat::
	.string "WAHAHAH! What power!\nYou beat me fair and square!$"

JohtoIsle_Chuck_Text_LeaderAfter::
	.string "Hoo-hah! My muscles are\nscreaming, and I love it!\pThat battle was worth a\nthousand hours under a falls!$"

JohtoIsle_Chuck_Text_LeaderPostBattle::
	.string "I train here till sundown,\nrain or shine. HWAAH!$"

JohtoIsle_Chuck_Text_SailorBlocked::
	.string "Ahoy! Beat this isle's GYM LEADER\n"
	.string "and I'll ferry you onward.$"

JohtoIsle_Chuck_Text_SailorOnward::
	.string "Ready to sail to the next isle?$"

JohtoIsle_Chuck_Text_SailorReturn::
	.string "Sail back to ONE ISLAND?$"

JohtoIsle_Chuck_Text_HoennBRAWLYPre::
	.string "I'm BRAWLY, of the HOENN\n"
	.string "LEAGUE. This isle tests us both!\p"
	.string "Show me your power!$"

JohtoIsle_Chuck_Text_HoennBRAWLYIntro::
	.string "Let's go!$"

JohtoIsle_Chuck_Text_HoennBRAWLYDefeat::
	.string "Whoa, total wipeout!\nYou rode that wave, dude.$"

JohtoIsle_Chuck_Text_HoennBRAWLYAfter::
	.string "You caught a wave I never\neven saw coming, man.\pI'm gonna train on IRONFIST\ntill I can ride it too!$"

JohtoIsle_Chuck_Text_HoennBRAWLYPostBattle::
	.string "Big swells out here today.\nCome ride them with me!$"
