JohtoIsle_Jasmine_Text_LeaderPreBattle::
	.string "I am JASMINE, master of this\n"
	.string "isle. Show me your resolve!$"

JohtoIsle_Jasmine_Text_LeaderIntro::
	.string "Let's battle!$"

JohtoIsle_Jasmine_Text_LeaderDefeat::
	.string "...Oh my. You're truly\nstrong. I can tell.$"

JohtoIsle_Jasmine_Text_LeaderAfter::
	.string "Um... that was wonderful.\nThank you for battling me.\pSteel is strong, but you\nwere stronger still.$"

JohtoIsle_Jasmine_Text_LeaderPostBattle::
	.string "The forges of FOUNDRY never\ncool... Please visit again.$"

JohtoIsle_Jasmine_Text_SailorBlocked::
	.string "Ahoy! Beat this isle's GYM LEADER\n"
	.string "and I'll ferry you onward.$"

JohtoIsle_Jasmine_Text_SailorOnward::
	.string "Ready to sail to the next isle?$"

JohtoIsle_Jasmine_Text_SailorReturn::
	.string "Sail back to ONE ISLAND?$"

JohtoIsle_Jasmine_Text_HoennROXANNEPre::
	.string "I'm ROXANNE, of the HOENN\n"
	.string "LEAGUE. This isle tests us both!\p"
	.string "Show me your power!$"

JohtoIsle_Jasmine_Text_HoennROXANNEIntro::
	.string "Let's go!$"

JohtoIsle_Jasmine_Text_HoennROXANNEDefeat::
	.string "So I lost... I have much\nmore to learn, it seems.$"

JohtoIsle_Jasmine_Text_HoennROXANNEAfter::
	.string "No textbook could have\nprepared me for that.\pI'll study our battle until\nI understand every move.$"

JohtoIsle_Jasmine_Text_HoennROXANNEPostBattle::
	.string "I'm writing up our battle for\nmy students. Thank you!$"
