CeruleanCave_B1F_Text_Mew::
    .string "Mew!$"


CeruleanCave_B1F_Text_SmithIntro::
	.string "SMITH: Shh… something incredible\n"
	.string "sleeps deeper in this cave.\p"
	.string "Only the strongest may pass me!$"

CeruleanCave_B1F_Text_SmithDefeat::
	.string "Legacy secured…!$"

CeruleanCave_B1F_Text_SmithPostBattle::
	.string "What waits below has no equal.\n"
	.string "Bring your best POKé BALLS.$"
