FuchsiaCity_PokemonCenter_1F_Text_CantBecomeGoodTrainerWithOneMon::
    .string "You can't become a good TRAINER\n"
    .string "with just one strong POKéMON.\p"
    .string "But raising many POKéMON evenly\n"
    .string "is no easy task, either.$"

FuchsiaCity_PokemonCenter_1F_Text_PokemonLeagueWestOfViridian::
    .string "There's a narrow trail west of\n"
    .string "VIRIDIAN CITY.\p"
    .string "It goes to the POKéMON LEAGUE HQ.\n"
    .string "The HQ governs all TRAINERS.$"

FuchsiaCity_PokemonCenter_1F_Text_VisitSafariZoneForPokedex::
    .string "If you're working on a POKéDEX,\n"
    .string "visit the SAFARI ZONE.\p"
    .string "All sorts of rare POKéMON breed\n"
    .string "there.$"


FuchsiaCity_PokemonCenter_1F_Text_NurseJoyGreeting::
    .string "Welcome to the POKéMON CENTER!\p"
    .string "I heal TRAINERS' POKéMON all day,\n"
    .string "but I trained a team of my own,\l"
    .string "too. Someday I'd love a real\l"
    .string "battle... once you're a CHAMPION.$"

FuchsiaCity_PokemonCenter_1F_Text_NurseJoyIntro::
    .string "You did it--you're the CHAMPION!\p"
    .string "Then the wait is over. Let me\n"
    .string "show you the team I've raised\l"
    .string "between healings. No holding back!$"

FuchsiaCity_PokemonCenter_1F_Text_NurseJoyDefeat::
    .string "Wonderful! Win or lose, a good\n"
    .string "battle is the best medicine.$"

FuchsiaCity_PokemonCenter_1F_Text_NurseJoyPostBattle::
    .string "Thank you for the battle!\p"
    .string "Now let me get back to work.\n"
    .string "Your POKéMON are always welcome\l"
    .string "here.$"
