PokemonMansion_Text_PressSecretSwitch::
    .string "A secret switch!\p"
    .string "Press it?$"

PokemonMansion_Text_WhoWouldnt::
    .string "Who wouldn't?$"

PokemonMansion_Text_NotQuiteYet::
    .string "Not quite yet!$"

PokemonMansion_1F_Text_ArnieIntro::
    .string "I can't get out!\n"
    .string "This old place is one big puzzle.$"

PokemonMansion_1F_Text_ArnieDefeat::
    .string "Oh, no!\n"
    .string "My bag of loot!$"

PokemonMansion_1F_Text_ArniePostBattle::
    .string "The switches here open and close\n"
    .string "alternating sets of doors.$"

PokemonMansion_1F_Text_NewMonDiscoveredInGuyanaJungle::
    .string "Diary: July 5\n"
    .string "Guyana, South America\p"
    .string "A new POKéMON was discovered deep\n"
    .string "in the jungle.$"

PokemonMansion_1F_Text_ChristenedDiscoveredMonMew::
    .string "Diary: July 10\n"
    .string "We christened the newly discovered\l"
    .string "POKéMON, MEW.$"


PokemonMansion_2F_Text_OakChallenge::
	.string "OAK: {PLAYER}, you came!\p"
	.string "This mansion is where MEWTWO\n"
	.string "was born from MEW's DNA…\p"
	.string "Before I tell you the rest, show\n"
	.string "me the trainer behind that POKéDEX!\p"
	.string "I was a trainer long before I was\n"
	.string "a researcher. Here I come!$"

PokemonMansion_2F_Text_OakDefeat::
	.string "…Magnificent!\n"
	.string "My research is in good hands.$"

PokemonMansion_2F_Text_OakAfterBattle::
	.string "OAK: That team of mine has guarded\n"
	.string "my research for thirty years.\p"
	.string "Now then… the journals here say\n"
	.string "MEW eluded every researcher.\p"
	.string "But just now, in the basement…\n"
	.string "I sensed something watching us.\p"
	.string "Go, {PLAYER}. Finish the POKéDEX\n"
	.string "once and for all!$"
