ViridianCity_Mart_Text_YouCameFromPallet::
    .string "Hey!\n"
    .string "You came from PALLET TOWN?$"

ViridianCity_Mart_Text_TakeThisToProfOak::
    .string "You know PROF. OAK, right?\p"
    .string "His order came in.\n"
    .string "Can I get you to take it to him?$"

ViridianCity_Mart_Text_ReceivedOaksParcelFromClerk::
    .string "{PLAYER} received OAK'S PARCEL\n"
    .string "from the POKéMON MART clerk.$"

ViridianCity_Mart_Text_SayHiToOakForMe::
    .string "Okay, thanks! Please say hi to\n"
    .string "PROF. OAK for me, too.$"

ViridianCity_Mart_Text_ShopDoesGoodBusinessInAntidotes::
    .string "This shop does good business in\n"
    .string "ANTIDOTES, I've heard.$"

ViridianCity_Mart_Text_GotToBuySomePotions::
    .string "I've got to buy some POTIONS.\p"
    .string "You never know when your POKéMON\n"
    .string "will need quick healing.$"


ViridianCity_Mart_Text_ImFishingGuruDoYouLikeToFish::
	.string "I'm the FISHING GURU!\n"
	.string "I simply Looove fishing!\p"
	.string "Do you like to fish?$"

ViridianCity_Mart_Text_GrandTakeThisAndFish::
	.string "Grand! I like your style!\p"
	.string "Take this and fish, young one!$"

ViridianCity_Mart_Text_ReceivedOldRodFromGuru::
	.string "{PLAYER} received an OLD ROD\n"
	.string "from the FISHING GURU!$"

ViridianCity_Mart_Text_FishingIsAWayOfLife::
	.string "Fishing is a way of life!\p"
	.string "From the seas to rivers, go out\n"
	.string "and land the big one!$"

ViridianCity_Mart_Text_OhThatsSoDisappointing::
	.string "Oh…\n"
	.string "That's so disappointing…$"

ViridianCity_Mart_Text_HowAreTheFishBiting::
	.string "Hello there, {PLAYER}!\p"
	.string "How are the fish biting?$"

ViridianCity_Mart_Text_NoRoomForThisGift::
	.string "Oh no!\p"
	.string "You have no room for this\n"
	.string "nice gift!$"
