JohtoIsle_Morty_Text_LeaderPreBattle::
	.string "I am MORTY, master of this\n"
	.string "isle. Show me your resolve!$"

JohtoIsle_Morty_Text_LeaderIntro::
	.string "Let's battle!$"

JohtoIsle_Morty_Text_LeaderDefeat::
	.string "I foresaw great power...\nI did not foresee this.$"

JohtoIsle_Morty_Text_LeaderAfter::
	.string "The spirits of HOLLOW said\na challenger would come.\pThey never said I would lose.\nPerhaps they were being kind.$"

JohtoIsle_Morty_Text_LeaderPostBattle::
	.string "The fog is thinning. The\nspirits are at peace with you.$"

JohtoIsle_Morty_Text_SailorBlocked::
	.string "Ahoy! Beat this isle's GYM LEADER\n"
	.string "and I'll ferry you onward.$"

JohtoIsle_Morty_Text_SailorOnward::
	.string "Ready to sail to the next isle?$"

JohtoIsle_Morty_Text_SailorReturn::
	.string "Sail back to ONE ISLAND?$"

JohtoIsle_Morty_Text_HoennTATELIZAPre::
	.string "I'm TATE&LIZA, of the HOENN\n"
	.string "LEAGUE. This isle tests us both!\p"
	.string "Show me your power!$"

JohtoIsle_Morty_Text_HoennTATELIZAIntro::
	.string "Let's go!$"

JohtoIsle_Morty_Text_HoennTATELIZADefeat::
	.string "TATE: Our minds...\nLIZA: ...weren't enough!$"

JohtoIsle_Morty_Text_HoennTATELIZAAfter::
	.string "TATE: We always know what\nLIZA: ...the other will do.\pTATE: But we couldn't read\nLIZA: ...even one of yours!$"

JohtoIsle_Morty_Text_HoennTATELIZAPostBattle::
	.string "TATE: Come battle us again!\nLIZA: ...we'll be ready!$"
